ci: fix issues with with ci
ignore internal merge commit of github
ignore tests if tests directory is not present

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,13 +51,15 @@ jobs:
 
       - name: Run tests
         run: |
-          for f in tests/*.snuk; do
-            echo "--- running $f"
-            ./build/snuk "$f"
-            if [ $? -ne 0 ]; then
-              echo "FAILED: $f"
-              exit 1
-            fi
-          done
+          if [ -d tests ]; then
+            for f in tests/*.snuk; do
+              echo "--- running $f"
+              ./build/snuk "$f"
+              if [ $? -ne 0 ]; then
+                echo "FAILED: $f"
+                exit 1
+              fi
+            done
+          fi
         shell: bash
 
